### PR TITLE
Update IDs

### PR DESCRIPTION
**Pull request by RafaelLyra8**
Remove the PAPU50 undulator from the SAPUCAIA beamline and rename the APU22 undulator prefix from the EMA prefix to the SAPUCAIA prefix.

### CODE REVIEW

**Comment by fernandohds564** [comment]
@RafaelLyra8 , we don't have a GUI for the IVUs yet?

**Comment by xresende** [comment]
> @RafaelLyra8 , we don't have a GUI for the IVUs yet?

we do have temporary GUI installed in the control room desktops connecting with original IVUs PVs. COMP should probably deploy today the new IOCs with updated PVs names for both IVUs. I think @RafaelLyra8 will work on the IVU Layout as soon as these PVs are avaiable (the names whould be the same as for the DELTA)

**Comment by fernandohds564** [comment]
> > @RafaelLyra8 , we don't have a GUI for the IVUs yet?
> 
> we do have temporary GUI installed in the control room desktops connecting with original IVUs PVs. COMP should probably deploy today the new IOCs with updated PVs names for both IVUs. I think @RafaelLyra8 will work on the IVU Layout as soon as these PVs are avaiable (the names whould be the same as for the DELTA)

I think he already added the IVU GUIs in his latest commits, right @RafaelLyra8 ?

**Review by fernandohds564 — APPROVED** [review]

**Comment by RafaelLyra8** [comment]
I only duplicated the code from the DELTA Layout while the IVU PVs are not in the Sirius PV name standardization, but I will probably need to do some improvements for specific IVU PVs.

**Review by murilobalves — APPROVED** [review]

**Pull request merged**
