### PR TITLE
Cryogenic plant GUI

### PR DESCRIPTION
**Pull request by RafaelLyra8**
image
image
image
image

### CODE REVIEW

**Review by rbatistacardoso — APPROVED** [review]

**Comment by fernandohds564** [comment]
@RafaelLyra8 , the color scheme and the relative sizes of the drawings and the text are not ideal. Also, the tabs on the lower part of the window are not what we usually do in our windows... Is there a reasoning behind these choices?

**Review by fernandohds564 — CHANGES_REQUESTED** [review]
@anacso17, @RafaelLyra8 , I noticed the PV naming style of this system differs significantly from our naming conventions. Is there a reason for that?

**Comment by anacso17** [comment]
> @RafaelLyra8 , the color scheme and the relative sizes of the drawings and the text are not ideal. Also, the tabs on the lower part of the window are not what we usually do in our windows... Is there a reasoning behind these choices?

Hi @fernandohds564 , this GUI was implemented to replicate the cryogenic plant IHM GUI. It was a requirement from HVR group, to reduce the learning curve of the support groups during this subsystem commissioning.

**Comment by anacso17** [comment]
> @anacso17, @RafaelLyra8 , I noticed the PV naming style of this system differs significantly from our naming conventions. Is there a reason for that?



> @anacso17, @RafaelLyra8 , I noticed the PV naming style of this system differs significantly from our naming conventions. Is there a reason for that?

Hi @fernandohds564 , for the same reason I mentioned above, the PV names were chosen in order to maintain maximum similarity with the IHM tags. We intend to improve this when we become more familiar with the subsystem.

**Review by fernandohds564 — APPROVED** [review]

**Review by rbatistacardoso — APPROVED** [review]

**Comment by xresende** [comment]
@RafaelLyra8 , in the first screen, Co tab, is there indications in the diagram which line is Coldbox1 and which line is Coldbox2 ?

**Review by xresende — APPROVED** [review]

**Comment by fernandohds564** [comment]
@RafaelLyra8 , remember to delete the merged branches.

**Pull request merged**
