### PR TITLE
Improve BPM and orbit interlock windows

### PR DESCRIPTION
**Pull request by anacso17**
This PR:
- Improve BPM detail windows with more advanced settings:

Screenshot from 2023-07-28 15-16-51
Screenshot from 2023-07-28 15-16-54
Screenshot from 2023-07-27 16-09-09
Screenshot from 2023-07-28 15-17-01
Screenshot from 2023-07-28 15-17-05
Screenshot from 2023-07-28 15-17-17

- Add minor improvements in Orbit interlock detail (title and minimum sum representation) and general (sum threshold setpoints) window 
Screenshot from 2023-07-27 16-07-58

Depends on https://github.com/lnls-sirius/dev-packages/pull/1002

### CODE REVIEW

**Comment by ericonr** [comment]
There's a weird issue with the MONIT Update time setting... The -SP and -RB are set to 0.005, but the interface *shows* 0.050 for the setpoint, even though the readback is correct. I tested that this happens for a BPM in our development crate as well. Furthermore, I am unable to set the PV to a value lower than 0.050.

**Review by murilobalves — APPROVED** [review]

**Comment by anacso17** [comment]
> There's a weird issue with the MONIT Update time setting... The -SP and -RB are set to 0.005, but the interface _shows_ 0.050 for the setpoint, even though the readback is correct. I tested that this happens for a BPM in our development crate as well. Furthermore, I am unable to set the PV to a value lower than 0.050.

This is happening probably because of the inconsistency of the values with the limits defined to this record... The widget for the SP PV (spinbox) uses the control/display limits to determine the minimum value that can be displayed. I can change the widget to a lineedit, probably it will appear okay, but I think this inconsistency should be solved in the IOC as well.

**Comment by fernandohds564** [comment]
> > There's a weird issue with the MONIT Update time setting... The -SP and -RB are set to 0.005, but the interface _shows_ 0.050 for the setpoint, even though the readback is correct. I tested that this happens for a BPM in our development crate as well. Furthermore, I am unable to set the PV to a value lower than 0.050.
> 
> This is happening probably because of the inconsistency of the values with the limits defined to this record... The widget for the SP PV (spinbox) uses the control/display limits to determine the minimum value that can be displayed. I can change the widget to a lineedit, probably it will appear okay, but I think this inconsistency should be solved in the IOC as well.

I think you don't need to downgrade the widget to lineedit. Can't you just set the limits in the code?

**Review by fernandohds564 — APPROVED** [review]

**Comment by ericonr** [comment]
> I think you don't need to downgrade the widget to lineedit. Can't you just set the limits in the code?

Ana and I talked about this, the issue is the pvdb has outdated limits (0.050 and 1.0), instead of the PV's actual configured limits (0.001 and 1.0).

**Comment by fernandohds564** [comment]
> > I think you don't need to downgrade the widget to lineedit. Can't you just set the limits in the code?
> 
> Ana and I talked about this, the issue is the pvdb has outdated limits (0.050 and 1.0), instead of the PV's actual configured limits (0.001 and 1.0).
> 
> She'll include a fix for that.

But if there's a limit in the PV I think we should not read it from the database we define in siriuspy. We should read it from the PV.

**Comment by anacso17** [comment]
@fernandohds564 @ericonr I pushed a commit that removes the dependency on BPM database defined in siriuspy and migrated all PVs that do not have limits defined to lineedit. Maybe (for future) a better solution is to change spinbox to define an arbitrary limit according to PV type, if the limits are not defined.

**Review by xresende — APPROVED** [review]

**Pull request merged**
