### PR TITLE
Update IDFF: remove PSSOFB and add CalcCorr widgets

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Comment by xresende** [comment]
maybe a widget grid with (CH, CV, QS) x (Corr1, Corr2) would look better. can you guys help with this ?

**Comment by anacso17** [comment]
> maybe a widget grid of (CH, CV, QS) x (Corr1, Corr2) `Current-Mon` values would look better. can you guys help with this ?

Hi @xresende , yes, we can help! We could try other options, bring some prints, and commit changes when we have a consensus

**Comment by xresende** [comment]
> > maybe a widget grid of (CH, CV, QS) x (Corr1, Corr2) `Current-Mon` values would look better. can you guys help with this ?
> 
> Hi @xresende , yes, we can help! We could try other options, bring some prints, and commit changes when we have a consensus

I tried the new IDFF IOC version (sabia is not using its ID) and tested OK the current IDFF window version.

**Comment by anacso17** [comment]
Hi @xresende , I tried a new layout, what do you think?
Screenshot from 2024-01-03 12-19-53

**Comment by xresende** [comment]
> Hi @xresende , I tried a new layout, what do you think? Screenshot from 2024-01-03 12-19-53

thanks, @anacso17 !

**Comment by xresende** [comment]
@RafaelLyra8 , can you review this PR please ?

**Pull request merged**
